server:
  port: 8861
spring:
  application:
    name: zuul-route-single
zuul:
  routes:
    api-a:
      path: /v1/**
      url: http://localhost:8764/
    api-b:
      path: /v2/**
      serviceId: api-b
api-b:
  ribbon:
    listOfServers: http://localhost:8765/, http://localhost:8766/